### ISSUE TITLE
Windows Package Manager Installation Check: $ProgramVersion_minimum

### ISSUE THREAD

**Issue by SwissSalaryBoris** [FlorianSLZ/Intune-Win32-Deployer#2]
https://github.com/FlorianSLZ/Intune-Win32-Deployer/blob/66670024b4991003e9976a2d70af5aa4fb25892c/source/apps-custom/Windows%20Package%20Manager/check.ps1#L12

`$ProgramVersion_minimum` is not set anywhere. So winget file version is always higher.

**Comment by taalexander0614** [comment]
When I try to deploy Windows Package Manager through Intune; it seems like it installs and then says it failed a few seconds later. The test under the Install button says this app is no longer detected on your devices. It may have been uninstalled...." Would this issue be what is causing that? I have had about 2 out of 20 computers install it and not come back with a failure after with the same deployment.

**Comment by FlorianSLZ** [comment]
Thanks for reporting, I've updatet the files to solve this.
